export type CheckGroup = "combat" | "movement" | "world" | "inventory" | "exploit";

export type CheckAction = "log" | "setback" | "kick" | "ban";

export interface CheckDefinition {
  id: string;
  label: string;
  group: CheckGroup;
  summary: string;
  enabled: boolean;
  action: CheckAction;
  threshold: number;
}

export const groupLabels: Record<CheckGroup, string> = {
  combat: "Combat",
  movement: "Movement",
  world: "World",
  inventory: "Inventory",
  exploit: "Exploit",
};

export const groupIcons: Record<CheckGroup, string> = {
  combat: "textures/ui/sword",
  movement: "textures/ui/speed_effect",
  world: "textures/ui/hammer_l",
  inventory: "textures/ui/glyph_inventory",
  exploit: "textures/ui/debug_glyph_color",
};

export const checkDefinitions: CheckDefinition[] = [
  {
    id: "reach",
    label: "Reach",
    group: "combat",
    summary: "Attacks landing from further than vanilla range allows",
    enabled: true,
    action: "setback",
    threshold: 6,
  },
  {
    id: "killAura",
    label: "Kill Aura",
    group: "combat",
    summary: "Attacking behind the player, through walls, or many targets at once",
    enabled: true,
    action: "setback",
    threshold: 5,
  },
  {
    id: "autoClicker",
    label: "Auto Clicker",
    group: "combat",
    summary: "Click rates and click spacing no human hand produces",
    enabled: true,
    action: "log",
    threshold: 8,
  },
  {
    id: "aimSnap",
    label: "Aim Snap",
    group: "combat",
    summary: "Instant head rotation onto a target on the tick of an attack",
    enabled: true,
    action: "log",
    threshold: 8,
  },
  {
    id: "selfHit",
    label: "Self Hit",
    group: "combat",
    summary: "A player registering itself as its own attacker",
    enabled: true,
    action: "setback",
    threshold: 3,
  },
  {
    id: "fly",
    label: "Fly",
    group: "movement",
    summary: "Airborne motion that ignores gravity",
    enabled: true,
    action: "setback",
    threshold: 5,
  },
  {
    id: "speed",
    label: "Speed",
    group: "movement",
    summary: "Ground speed above what sprinting and effects can produce",
    enabled: true,
    action: "setback",
    threshold: 6,
  },
  {
    id: "noClip",
    label: "No Clip",
    group: "movement",
    summary: "Moving while the body is inside a solid block",
    enabled: true,
    action: "setback",
    threshold: 4,
  },
  {
    id: "highJump",
    label: "High Jump",
    group: "movement",
    summary: "Jump height beyond what the jump boost level allows",
    enabled: true,
    action: "setback",
    threshold: 5,
  },
  {
    id: "noSlow",
    label: "No Slow",
    group: "movement",
    summary: "Full movement speed while eating, drawing a bow, or sneaking",
    enabled: true,
    action: "log",
    threshold: 8,
  },
  {
    id: "antiKnockback",
    label: "Anti Knockback",
    group: "movement",
    summary: "Absorbing knockback that should have moved the player",
    enabled: true,
    action: "log",
    threshold: 6,
  },
  {
    id: "nuker",
    label: "Nuker",
    group: "world",
    summary: "Breaking more blocks per second than a player can reach",
    enabled: true,
    action: "setback",
    threshold: 4,
  },
  {
    id: "scaffold",
    label: "Scaffold",
    group: "world",
    summary: "Bridging blocks placed behind the player while facing away",
    enabled: true,
    action: "setback",
    threshold: 6,
  },
  {
    id: "fastBreak",
    label: "Fast Break",
    group: "world",
    summary: "Blocks broken faster than the held tool permits",
    enabled: true,
    action: "setback",
    threshold: 5,
  },
  {
    id: "blockReach",
    label: "Block Reach",
    group: "world",
    summary: "Breaking or placing blocks outside of interaction range",
    enabled: true,
    action: "setback",
    threshold: 5,
  },
  {
    id: "xray",
    label: "X Ray",
    group: "world",
    summary: "Ore mining ratios that suggest the player can see through stone",
    enabled: true,
    action: "log",
    threshold: 4,
  },
  {
    id: "illegalItems",
    label: "Illegal Items",
    group: "inventory",
    summary: "Overstacked items, impossible enchant levels, and banned items",
    enabled: true,
    action: "setback",
    threshold: 1,
  },
  {
    id: "autoTotem",
    label: "Auto Totem",
    group: "inventory",
    summary: "Totems moved into the offhand faster than a menu allows",
    enabled: true,
    action: "log",
    threshold: 5,
  },
  {
    id: "chestAura",
    label: "Chest Aura",
    group: "inventory",
    summary: "Containers opened from outside of interaction range",
    enabled: true,
    action: "setback",
    threshold: 4,
  },
  {
    id: "nameSpoof",
    label: "Name Spoof",
    group: "exploit",
    summary: "Player names carrying formatting codes or impossible lengths",
    enabled: true,
    action: "kick",
    threshold: 1,
  },
  {
    id: "gameMode",
    label: "Game Mode",
    group: "exploit",
    summary: "Non staff sitting in creative or spectator",
    enabled: true,
    action: "setback",
    threshold: 1,
  },
  {
    id: "badPackets",
    label: "Bad Packets",
    group: "exploit",
    summary: "Positions and rotations outside of anything the client can send",
    enabled: true,
    action: "setback",
    threshold: 3,
  },
];
