export const combatTuning = {
  maxAttackDistance: 3.6,
  maxAttackAngle: 95,
  auraTargetWindow: 12,
  auraTargetCount: 3,
  wallCheckMinDistance: 1.8,
  maxClicksPerSecond: 17,
  clickSampleSize: 12,
  minClickDeviation: 9,
  aimSnapDegrees: 42,
  aimSnapPitchDegrees: 28,
};

export const movementTuning = {
  minAirTicks: 12,
  ascendStreakNeeded: 6,
  hoverTolerance: 0.005,
  hoverStreakNeeded: 20,
  glideAirTicks: 40,
  glideFallRate: -0.05,
  glideStreakNeeded: 15,
  walkSpeed: 0.22,
  sprintSpeed: 0.29,
  speedEffectBonus: 0.2,
  momentumSpeed: 0.42,
  iceSpeed: 0.68,
  speedStreakNeeded: 5,
  baseJumpHeight: 1.35,
  jumpBoostHeight: 0.55,
  noClipStreakNeeded: 3,
  itemUseSpeed: 0.14,
  sneakSpeed: 0.14,
  knockbackWindow: 4,
  knockbackMinimum: 0.08,
};

export const worldTuning = {
  maxBlockDistance: 7.5,
  nukerWindow: 3,
  nukerSpread: 3.5,
  scaffoldAngle: 105,
  scaffoldMinSpeed: 0.14,
  xraySampleSize: 90,
  xrayOreRatio: 0.16,
  xrayResetTicks: 24000,
  breakSpeedTolerance: 0.55,
};

export const inventoryTuning = {
  scanInterval: 120,
  totemSwapTicks: 5,
  containerWindow: 40,
  containerCount: 4,
};

export const exploitTuning = {
  maxNameLength: 24,
  worldLimit: 30000000,
  maxPitch: 90.5,
};

export const bannedItems = [
  "minecraft:command_block",
  "minecraft:chain_command_block",
  "minecraft:repeating_command_block",
  "minecraft:command_block_minecart",
  "minecraft:structure_block",
  "minecraft:structure_void",
  "minecraft:jigsaw",
  "minecraft:barrier",
  "minecraft:light_block",
  "minecraft:allow",
  "minecraft:deny",
  "minecraft:border_block",
  "minecraft:bedrock",
  "minecraft:end_portal_frame",
  "minecraft:budding_amethyst",
  "minecraft:spawner",
  "minecraft:mob_spawner",
  "minecraft:reinforced_deepslate",
];

export const oreBlocks = [
  "minecraft:diamond_ore",
  "minecraft:deepslate_diamond_ore",
  "minecraft:ancient_debris",
  "minecraft:emerald_ore",
  "minecraft:deepslate_emerald_ore",
  "minecraft:gold_ore",
  "minecraft:deepslate_gold_ore",
  "minecraft:nether_gold_ore",
  "minecraft:iron_ore",
  "minecraft:deepslate_iron_ore",
  "minecraft:lapis_ore",
  "minecraft:deepslate_lapis_ore",
  "minecraft:redstone_ore",
  "minecraft:deepslate_redstone_ore",
  "minecraft:lit_redstone_ore",
  "minecraft:lit_deepslate_redstone_ore",
  "minecraft:copper_ore",
  "minecraft:deepslate_copper_ore",
  "minecraft:quartz_ore",
];

export const stoneBlocks = [
  "minecraft:stone",
  "minecraft:deepslate",
  "minecraft:cobblestone",
  "minecraft:cobbled_deepslate",
  "minecraft:andesite",
  "minecraft:diorite",
  "minecraft:granite",
  "minecraft:tuff",
  "minecraft:netherrack",
  "minecraft:basalt",
  "minecraft:blackstone",
  "minecraft:dirt",
  "minecraft:gravel",
];

export const blockHardness: Record<string, number> = {
  "minecraft:obsidian": 50,
  "minecraft:crying_obsidian": 50,
  "minecraft:respawn_anchor": 50,
  "minecraft:ancient_debris": 30,
  "minecraft:netherite_block": 50,
  "minecraft:enchanting_table": 5,
  "minecraft:anvil": 5,
  "minecraft:iron_block": 5,
  "minecraft:gold_block": 3,
  "minecraft:diamond_block": 5,
  "minecraft:emerald_block": 5,
  "minecraft:coal_block": 5,
  "minecraft:stone": 1.5,
  "minecraft:deepslate": 3,
  "minecraft:cobblestone": 2,
  "minecraft:cobbled_deepslate": 3.5,
  "minecraft:stone_bricks": 1.5,
  "minecraft:deepslate_bricks": 3.5,
  "minecraft:end_stone": 3,
  "minecraft:end_stone_bricks": 0.8,
  "minecraft:iron_ore": 3,
  "minecraft:deepslate_iron_ore": 4.5,
  "minecraft:gold_ore": 3,
  "minecraft:deepslate_gold_ore": 4.5,
  "minecraft:diamond_ore": 3,
  "minecraft:deepslate_diamond_ore": 4.5,
  "minecraft:emerald_ore": 3,
  "minecraft:deepslate_emerald_ore": 4.5,
  "minecraft:redstone_ore": 3,
  "minecraft:deepslate_redstone_ore": 4.5,
  "minecraft:lapis_ore": 3,
  "minecraft:deepslate_lapis_ore": 4.5,
  "minecraft:copper_ore": 3,
  "minecraft:deepslate_copper_ore": 4.5,
  "minecraft:oak_log": 2,
  "minecraft:spruce_log": 2,
  "minecraft:birch_log": 2,
  "minecraft:jungle_log": 2,
  "minecraft:acacia_log": 2,
  "minecraft:dark_oak_log": 2,
  "minecraft:cherry_log": 2,
  "minecraft:mangrove_log": 2,
  "minecraft:oak_planks": 2,
  "minecraft:chest": 2.5,
  "minecraft:crafting_table": 2.5,
  "minecraft:furnace": 3.5,
  "minecraft:blast_furnace": 3.5,
  "minecraft:hopper": 3,
  "minecraft:beacon": 3,
  "minecraft:ender_chest": 22.5,
  "minecraft:packed_ice": 0.5,
  "minecraft:brick_block": 2,
  "minecraft:nether_bricks": 2,
  "minecraft:quartz_block": 0.8,
  "minecraft:sandstone": 0.8,
  "minecraft:prismarine": 1.5,
  "minecraft:purpur_block": 1.5,
};

export const toolSpeeds: Record<string, number> = {
  wooden: 2,
  stone: 4,
  iron: 6,
  golden: 12,
  diamond: 8,
  netherite: 9,
};
