export const icons = {
  players: "textures/ui/icon_multiplayer",
  checks: "textures/ui/settings_glyph_color_2x",
  logs: "textures/ui/icon_book_writable",
  bans: "textures/ui/icon_lock",
  status: "textures/ui/icon_timer",
  general: "textures/ui/icon_setting",
  about: "textures/ui/glyph_realms",
  back: "textures/ui/book_arrowleft_default",
  refresh: "textures/ui/refresh",
  clear: "textures/ui/trash",
  staff: "textures/ui/permissions_op_crown",
  player: "textures/ui/icon_steve",
  freeze: "textures/ui/lock",
  kick: "textures/ui/realms_red_x",
  ban: "textures/ui/ErrorGlyph",
  enabled: "textures/ui/check",
  disabled: "textures/ui/cancel",
  warning: "textures/ui/WarningGlyph",
};
